### ISSUE TITLE
Beschrijving van het spel

### ISSUE THREAD

**Issue by StephanStanisic** [StephanStanisic/In2game#5]
Hierin geef je een opsomming met de uitleg van het algemene thema, het doel en de gameplay van het spel.  
Probeer de lengte van dit onderdeel krt te houden omdat er in dit stadium nog niet de noodzaak bestaat om heel erg in details te treden.

**Comment by kjeldvdl** [comment]
Het spel wordt een top to down shooter game waarbij je moet proberen om enemy's en bosses te verslaan om naar een volgend leven (layer) te gaan. Elke keer nadat je een boss hebt verslagen kan je kiezen tussen upgrades van je stats. Het wordt een random seed based game zodat je steeds een ander level hebt. Hierdoor kan je steeds maar blijven spelen en nieuwe dingen ontdekken.
