### ISSUE TITLE
Inventarisatie game objecten

### ISSUE THREAD

**Issue by StephanStanisic** [StephanStanisic/In2game#6]

**Comment by StephanStanisic** [comment]
https://github.com/StephanStanisic/In2game/blob/master/Carbon/Game%20Design%20Document/14.jpg
https://github.com/StephanStanisic/In2game/blob/master/Carbon/Game%20Design%20Document/15.jpg

**Comment by cooleJMJ** [comment]
Player:
een viking die bestuurt  word door de speller en alle kanten op kan lopen ook heeft heeft hij een boog waarmee hij de vijand kan beschieten (dit doet de speller ook)

**Comment by cooleJMJ** [comment]
blobje:
een enemy een soort slijm monster die probeert de speller aan te vallen we weten nog niet hoeveel levens en damage deze doet

**Comment by cooleJMJ** [comment]
happybean:
een enemy die lijkt op een boontje met een gezicht die probeert de speller aan te vallen
![happybean](https://user-images.githubusercontent.com/32064479/31084495-d7dad138-a794-11e7-990e-e25f491c9bd1.png)

**Comment by cooleJMJ** [comment]
skelly:
een enemy die lijkt op een lopend skelet die de player aanvalt een zwaard of met de hand/bot
![skelly](https://user-images.githubusercontent.com/32064479/31084892-f3182076-a795-11e7-82c1-bc28879f6f31.png)

**Comment by cooleJMJ** [comment]
orc:
een orc die probeert de speller aan te vallen met een zwaard

**Comment by cooleJMJ** [comment]
orc:
een orc is een enemy die de player aanvalt met een zwaard
