### ISSUE TITLE
Schermbeschrijvingen

### ISSUE THREAD

**Issue by StephanStanisic** [StephanStanisic/In2game#8]

**Comment by kjeldvdl** [comment]
Splash screen: Op dit scherm zie de naam van het spel en de makers en een plaatje
Menu items: Start een spel, Controls , Score, Credits
How to play: Je loopt met WASD en schiet met Pijltjes toetsen.

**Comment by StephanStanisic** [comment]
[GameAactionSequence.pdf](https://github.com/StephanStanisic/In2game/files/1349597/GAS.pdf)

**Comment by StephanStanisic** [comment]
https://github.com/StephanStanisic/In2game/blob/master/Carbon/Game%20Design%20Document/GAS.pdf
